// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6UNnlFop7pPz1Xtq-TnPmIDF7jN4ELBQ',
    appId: '1:543968355606:web:a217043281d621ac955c37',
    messagingSenderId: '543968355606',
    projectId: 'al-qur-an-92b08',
    authDomain: 'al-qur-an-92b08.firebaseapp.com',
    storageBucket: 'al-qur-an-92b08.firebasestorage.app',
    measurementId: 'G-ZC8JF7ZYH6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQB7mSzf6-0wzqMV6h9N2Uuq1glkgK43s',
    appId: '1:543968355606:android:a63af2993ba3afc9955c37',
    messagingSenderId: '543968355606',
    projectId: 'al-qur-an-92b08',
    storageBucket: 'al-qur-an-92b08.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDp0Lkof1LUglDvMnfD2WShu7F7HcRkUHE',
    appId: '1:543968355606:ios:dd76fa7979a4e378955c37',
    messagingSenderId: '543968355606',
    projectId: 'al-qur-an-92b08',
    storageBucket: 'al-qur-an-92b08.firebasestorage.app',
    androidClientId: '543968355606-d1k0vdpnb5u4cbht96al0pon2vo8jn7m.apps.googleusercontent.com',
    iosClientId: '543968355606-colb6kr6j4bc5i5d5ijht00lig4uut8q.apps.googleusercontent.com',
    iosBundleId: 'com.example.quranApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDp0Lkof1LUglDvMnfD2WShu7F7HcRkUHE',
    appId: '1:543968355606:ios:dd76fa7979a4e378955c37',
    messagingSenderId: '543968355606',
    projectId: 'al-qur-an-92b08',
    storageBucket: 'al-qur-an-92b08.firebasestorage.app',
    androidClientId: '543968355606-d1k0vdpnb5u4cbht96al0pon2vo8jn7m.apps.googleusercontent.com',
    iosClientId: '543968355606-colb6kr6j4bc5i5d5ijht00lig4uut8q.apps.googleusercontent.com',
    iosBundleId: 'com.example.quranApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6UNnlFop7pPz1Xtq-TnPmIDF7jN4ELBQ',
    appId: '1:543968355606:web:3060bd1dee9e601e955c37',
    messagingSenderId: '543968355606',
    projectId: 'al-qur-an-92b08',
    authDomain: 'al-qur-an-92b08.firebaseapp.com',
    storageBucket: 'al-qur-an-92b08.firebasestorage.app',
    measurementId: 'G-RZZDPK2W1Z',
  );

}